--
-- Author: Your Name
-- Date: 2017-12-19 22:27:13
--

--_DEBUG_QUICK_ENTER_GAME = true
_DEBUG_LOGIN_ACCOUNT = "chenshao01"
_DEBUG_LOGIN_PWD     = "chb123"
_DEBUG_SELECTED_TABLEID = 0
_DEBUG_SELECTED_CHAIRID = 0

--_DEBUG_QUICK_LOGIN = true

--_DEBUG_SHOP = true

--LAUNCH_SCENE = LOBBY_SCENE
